apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ceph-cluster
  namespace: kube-system
spec:
  chart: rook-ceph-cluster
  version: "v1.17.1"
  repo: "https://charts.rook.io/release"
  targetNamespace: rook-ceph
  createNamespace: true
  valuesContent: |-
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    clusterName: ceph-cluster
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v19.2.2
        allowUnsupported: false
      dataDirHostPath: /var/lib/rook
      dashboard:
        enabled: true
        ssl: false
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
      storage:
        useAllNodes: true
        useAllDevices: false
        devicePathFilter: "mapper/ceph--cluster-bluestore--.*"
        config:
          osdPoolDefaultSize: "1"
          osdPoolDefaultMinSize: "1"
