apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ceph-cluster
  namespace: kube-system
spec:
  chart: rook-ceph-cluster
  version: "v1.17.1"
  repo: "https://charts.rook.io/release"
  targetNamespace: rook-ceph
  createNamespace: true
  valuesContent: |-
    operatorNamespace: rook-ceph
    clusterName: ceph-cluster
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v19.2.2
        allowUnsupported: false
      dataDirHostPath: /var/lib/rook
      cleanupPolicy:
        confirmation: "yes-really-destroy-data"
        sanitizeDisks:
          method: quick
          dataSource: zero
          iteration: 1
      dashboard:
        enabled: true
        ssl: false
        service:
          type: NodePort
          nodePort: 32080
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
      storage:
        useAllNodes: true
        useAllDevices: false
        devicePathFilter: "mapper/ceph--primary--storage-bluestore--.*"
        config:
          osdPoolDefaultSize: "1"
          osdPoolDefaultMinSize: "1"
