apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ceph-cluster
  namespace: kube-system
spec:
  chart: rook-ceph-cluster
  version: "v1.17.1"
  repo: "https://charts.rook.io/release"
  targetNamespace: rook-ceph
  createNamespace: true
  valuesContent: |-
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    clusterName: ceph-cluster
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v19.2.2
        allowUnsupported: false
      dataDirHostPath: /var/lib/rook
      dashboard:
        enabled: true
        ssl: false
        urlPrefix: "/ceph-cluster"
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
      storage:
        useAllNodes: true
        useAllDevices: false
        devicePathFilter: "mapper/ceph--cluster-bluestore--.*"
        config:
          osdPoolDefaultSize: "1"
          osdPoolDefaultMinSize: "1"
    cephBlockPools:
      - name: blk-single-replica
        spec:
          failureDomain: host
          replicated:
            size: 1
        storageClass:
          enabled: true
          name: blk-single-replica
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            blockPool: blk-single-replica
            clusterID: ceph-cluster
            fstype: ext4
            imageFeatures: layering
          provisioner: rook-ceph.rbd.csi.ceph.com
    cephFileSystems: {}
    cephObjectStores: {}
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "standard"
        host:
          pathType: Prefix
          path: "/ceph-cluster(/|$)(.*)"
