apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart: cilium
  version: v1.17.3
  repo: https://helm.cilium.io
  targetNamespace: cilium
  createNamespace: true
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    operator:
      replicas: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        replicas: 1
        service:
          type: NodePort
        baseUrl: "/hubble/"
        ingress:
          enabled: false
          className: "nginx"
