apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ceph-cluster
  namespace: kube-system
spec:
  chart: rook-ceph-cluster
  repo: https://charts.rook.io/release
  version: v1.17.0
  targetNamespace: kube-system
  createNamespace: true
  valuesContent: |-
    ceph:
    storage:
      useAllNodes: true
      useAllDevices: true
      deviceFilter:
        - "/dev/sd[a-z]"