apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    operator:
      replicas: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        replicas: 1
        service:
          type: NodePort
        baseUrl: "/hubble/"
        ingress:
          className: "ngnix"
          enabled: true
          hosts:
           - 127-0-0-1.sslip.io
