apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    operator:
      replicas: 1
    hubble:
      enabled: true
      replicas: 1
      relay:
        enabled: true
      ui:
        enabled: true
        service:
          type: NodePort
