apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-operator
  namespace: kube-system
spec:
  chart: rook-ceph
  version: v1.17.0
  repo: https://charts.rook.io/release
  targetNamespace: rook-ceph
  createNamespace: true
