apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-operator
  namespace: kube-system
spec:
  chart: rook-operator
  version: v1.17.1
  repo: https://charts.rook.io/release
  targetNamespace: rook-ceph
  createNamespace: true
  valuesContent: |-
    crds:
      enabled: true
    csi:
      provisionerReplicas: 1
